name: WarpBuf

on:
  # pull_request: {}
  push:
    # branches:
      # - main
    paths:
      - 'WarpBuf/**'

jobs:

  build-all-platforms:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-x86_64
            os: ubuntu-20.04
          - name: macos-x86_64
            os: macos-11
          - name: win64
            os: windows-2022

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install autoconf autogen automake build-essential libasound2-dev \
        libflac-dev libogg-dev libtool libvorbis-dev libopus-dev libmp3lame-dev \
        libmpg123-dev pkg-config python

    - name: Install dependencies macOS
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install autoconf autogen automake flac libogg libtool libvorbis opus mpg123 pkg-config

    - name: Build release
      shell: bash
      run: |
        cd WarpBuf
        sh build_all_platforms.sh

    - name: Package release (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        mv WarpBuf/build/libWarpBuf.dylib WarpBuf/build/WarpBuf.chug 

    - name: Package release (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        mv WarpBuf/build/x64/Release/WarpBuf.dll WarpBuf/build/WarpBuf.chug 

    - name: Package release (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        mv WarpBuf/build/libWarpBuf.so WarpBuf/build/WarpBuf.chug

    - uses: actions/upload-artifact@v3
      with:
        name: warpbuf-${{ matrix.name }}.zip
        path: "WarpBuf/build/WarpBuf.chug"
        if-no-files-found: error
